### ISSUE TITLE
Can only register 5 blocks?!

### ISSUE THREAD

**Issue by alicam** [benplum/ACF-Auto-Blocks#1]
Ben.

I am investigating, but at the moment it only lets me register five blocks. Any more than 5 and the oldest ones (after the youngest 5) are ignored!

Everything looks fine on in the Custom Fields admin pages, but they just don't register.

Can you have a quick look? This is critical for a project I'm working on!

Cheers

A

**Comment by alicam** [comment]
ACF_Auto_Blocks::get_auto_blocks() returns 5 results, when I have 7 registered, of 9 field groups in total.

![image](https://user-images.githubusercontent.com/44537/51359227-e402d000-1b1a-11e9-856e-45e86e7c2ff0.png)

**Comment by alicam** [comment]
Sorry, I'm using the  latest ACF beta, with WordPress nightly (5.0.4-alpha-44523).

**Comment by alicam** [comment]
Ok fixed it.

```
 // Get auto blocks
  public function get_auto_blocks() {
    // TODO optimize this?
    $auto_blocks = get_posts( array(
      'post_type' => 'acf-field-group',
      'posts_per_page' => -1,
      'meta_key' => '_auto_block',
      'meta_value' => 'on',
    ) );

    return $auto_blocks;
  }
```

You needed to add an "s" to posts_per_page and get_posts doesn't need/use a meta_query sub-array. I think that's the gist of it. Anyway, it works now!

Phew!

A

**Comment by benplum** [comment]
Thanks! Will you be submitting a pull request?
