### ISSUE TITLE
Missing some support features

### ISSUE THREAD

**Issue by jvdh** [benplum/ACF-Auto-Blocks#4]
Hi Ben,

Great plugin. I'm missing some new features of ACF 5.9, like:
- Innerblocks
- Text alignment
- Content Alignment
https://www.advancedcustomfields.com/blog/acf-5-9-0-release-inner-blocks-ui-improvements-and-exciting-features/

also the ability to enque css/js 

These would be a great addition I think.

**Comment by benplum** [comment]
This has been added in [1.2.0](https://github.com/benplum/ACF-Auto-Blocks/releases/tag/1.2.0).
